### ISSUE TITLE
Can't delete widget after adding it

### ISSUE THREAD

**Issue by programmingkidx** [wxGlade/wxGlade#448]
When I add a widget to a gridsizer, the widget goes on and has the selection rectangles around it. When I try to delete it nothing happens. I have to unselect the widget by clicking somewhere else, then click on the widget to make it selected. After that I am able to delete the widget.

Steps to reproduce:
Add a Frame.
Add a Gridsizer.
Add a StaticText without causing it to become unselected.
Push the Delete button.

Nothing happens is the result.
What should happen is the widget should be removed.

**Comment by DietmarSchwertberger** [comment]
Thanks. It should be fixed now. I have just tested on Windows, though.

**Comment by programmingkidx** [comment]
Sorry but the problem is still present. I tried pushing the delete button, right clicking on the widget and selecting cut or Remove Widget. Nothing would work.

**Comment by DietmarSchwertberger** [comment]
I have added code to improve focus handling, but other than that I could not see an issue here.
This could be a bug in wxPython for macOS. Some time ago I got a report about issues and recently I had the situation where keys and menu selections would be only delivered after some other event happened. This went away as it came...

**Comment by DietmarSchwertberger** [comment]
Thanks. Pleaset try again. Now it should be more robust.

**Comment by programmingkidx** [comment]
I added a Frame.
Then I added a Gridsizer to Slot 0.
Then I added a button.
When I moved the button from one location to another this happened:

ERROR   : None
An unexpected error occurred!

Exception type:      <type 'exceptions.ValueError'>
Exception details:   <button.button.EditButton object at 0x104e45090> is not in list

Application stack traceback:
  File "/usr/local/lib/wxPython-3.0.2.0/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/_misc.py", line 1367, in Notify
    self.notify()
  File "/usr/local/lib/wxPython-3.0.2.0/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/_core.py", line 16869, in Notify
    self.result = self.callable(*self.args, **self.kwargs)
  File "/Users/misbah/Desktop/wxGlade-master/clipboard.py", line 222, in _OnData
    src_widget.remove()
  File "/Users/misbah/Desktop/wxGlade-master/edit_windows.py", line 732, in remove
    slot = self._remove()
  File "/Users/misbah/Desktop/wxGlade-master/edit_windows.py", line 727, in _remove
    return self.parent._free_slot(self.index)
  File "/Users/misbah/Desktop/wxGlade-master/edit_base.py", line 216, in index
    return self.parent.children.index(self)

Date and time:       2020-10-20T16:22:09.447417
Python version:      2.7.2
wxPython version:    3.0.2.0
wxWidgets platform:  __WXMAC__
wxGlade version:     1.0.0a9

**Comment by DietmarSchwertberger** [comment]
OK, on Windows it seems to work I will check macOS.

**Comment by DietmarSchwertberger** [comment]
With Python 3 and a recent wxPython everything seems to work on macOS. With Python 2 and wxPython 3.0.3 I can also see several problem, especially the delayed event handling. I will have a closer look in the next days, but I would guess it's bugs in wx/Python.
Maybe it's time to declare Python 2 and wxPython 3 on macOS as unsupported. These versions are rather historic nowadays...

**Comment by DietmarSchwertberger** [comment]
I would guess that this is a bug in wxPython which delays event handling. On 3.0.3 I did see it only once. There's nothing I could do, as there is no installable version where these could be reproduced. There is installable version of 3.0.2 available any more. If you can provide me with a 3.0.2 and this reproducibly fails, I can fix it.
If you continue to see these problems, please upgrade to some recent versions.

**Comment by programmingkidx** [comment]
Here is the installer for wxPython 3.0.2.0: https://sourceforge.net/projects/wxpython/files/wxPython/3.0.2.0/

**Comment by DietmarSchwertberger** [comment]
That does not work. I have re-packaged it acc. to these instructions: https://stackoverflow.com/questions/34402303/install-wxpython-in-osx-10-11/34622956#34622956

I don't see problems with the event handling, though.

**Comment by programmingkidx** [comment]
I am able to use the 3.0.2.0 installer on Mac OS 10.8. Which version of Mac OS X are you testing on?

**Comment by DietmarSchwertberger** [comment]
Wow, that's eight years old...
I'm currently testing on 10.14.
It seems the new installer mechanisms were introduced around 2015 with 10.11.
